name: cz

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: Bump version and create changelog with commitizen
    steps:
      - name: Check out
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          changelog_increment_filename: release-notes.md
      - name: Release
        if: "${{ env.REVISION != '' }}"
        run: |
          gh release create "${{ env.REVISION }}" --notes "$(cat release-notes.md)"
          gh workflow run compile-and-upload -f ref="${{ env.REVISION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
